_wandb:
    value:
        cli_version: 0.21.0
        e:
            3feh0ru54k0ewnkt2bv9riubejfbowbj:
                codePath: models\model_main\train.py
                codePathLocal: train.py
                cpu_count: 6
                cpu_count_logical: 12
                cudaVersion: "12.7"
                disk:
                    /:
                        total: "411440345088"
                        used: "256650326016"
                email: aguechfirass100@gmail.com
                executable: C:\Users\AGFirass\Documents\GitHub\Transformer-Based-DDoS-Detection\venv\Scripts\python.exe
                git:
                    commit: 22ed5720d95c5cf5eeb6bd96b43966d5c157d935
                    remote: git@github.com:aguechfirass100/Transformer-Based-DDoS-Detection.git
                gpu: NVIDIA GeForce RTX 3050 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 2048
                      memoryTotal: "4294967296"
                      name: NVIDIA GeForce RTX 3050 Laptop GPU
                      uuid: GPU-0f00a904-32f8-20aa-4ef1-01d0c062ec79
                host: AGF-Desktop
                memory:
                    total: "16893382656"
                os: Windows-10-10.0.26100-SP0
                program: C:\Users\AGFirass\Documents\GitHub\Transformer-Based-DDoS-Detection\models\model_main\train.py
                python: CPython 3.9.21
                root: ./checkpoints
                startedAt: "2025-08-18T14:16:43.271789Z"
                writerId: 3feh0ru54k0ewnkt2bv9riubejfbowbj
        m:
            - "1": trainer/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.9.21
        t:
            "1":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 103
            "2":
                - 1
                - 5
                - 9
                - 41
                - 53
                - 103
            "3":
                - 7
                - 66
            "4": 3.9.21
            "5": 0.21.0
            "8":
                - 2
                - 3
            "12": 0.21.0
            "13": windows-amd64
