data:
#  data_file: "C:/Users/AGFirass/Documents/GitHub/Transformer-Based-DDoS-Detection/data/subset/01-12/flow-level/combined_subset.parquet"
#  data_file: "C:/Users/AGFirass/Documents/GitHub/Transformer-Based-DDoS-Detection/notebooks/data_20k.parquet"
  data_file: "C:/Users/AGFirass/Documents/GitHub/Transformer-Based-DDoS-Detection/notebooks/IFT_data_ordered.parquet"
  label_column: "Label"
  train_fraction: 0.8
  val_fraction: 0.1
  test_fraction: 0.1

model:
  embed_dim: 64
  num_heads: 4
  num_layers: 3
  ffn_dim: 128
  dropout: 0.2
  num_classes: 6

training:
  batch_size: 256
  learning_rate: 1e-4
  epochs: 30
  gpus: 1

early_stopping:
  monitor: val_loss
  patience: 5
  mode: min

output_dir: "C:/Users/AGFirass/Documents/GitHub/Transformer-Based-DDoS-Detection/models/model_basic/lightning_logs"
